"""Core domain primitives for the Solo Wargame AI engine."""

from .enums import (
    CoordinateSystem,
    HexDirection,
    coordinate_system_from_name,
    hex_direction_from_name,
)
from .hexgrid import (
    ALL_DIRECTIONS,
    AXIAL_DIRECTION_DELTAS,
    BRITISH_FORWARD_DIRECTIONS,
    HexCoord,
    are_adjacent,
    british_forward_neighbors,
    neighbor,
    neighbors,
)
from .mission import (
    AttackProfile,
    AttackRange,
    BritishMissionData,
    BritishUnitClass,
    BritishUnitDefinition,
    CombatModifiers,
    EnemyRevealTableRow,
    GermanMissionData,
    GermanUnitClass,
    HiddenMarker,
    MapHex,
    Mission,
    MissionMap,
    MissionObjective,
    MissionObjectiveKind,
    MissionSource,
    MissionTurns,
    OrderName,
    OrdersChart,
    OrdersChartRow,
    attack_range_from_name,
    mission_objective_kind_from_name,
    order_name_from_name,
)
from .rng import DeterministicRNG, RNGState
from .terrain import TerrainType, is_terrain_name, terrain_from_name
from .validation import MissionValidationError, ValidationIssue, validate_mission

__all__ = [
    "ALL_DIRECTIONS",
    "AXIAL_DIRECTION_DELTAS",
    "AttackProfile",
    "AttackRange",
    "BRITISH_FORWARD_DIRECTIONS",
    "BritishMissionData",
    "BritishUnitClass",
    "BritishUnitDefinition",
    "CombatModifiers",
    "CoordinateSystem",
    "DeterministicRNG",
    "EnemyRevealTableRow",
    "GermanMissionData",
    "GermanUnitClass",
    "HiddenMarker",
    "HexCoord",
    "HexDirection",
    "MapHex",
    "Mission",
    "MissionMap",
    "MissionObjective",
    "MissionObjectiveKind",
    "MissionSource",
    "MissionTurns",
    "MissionValidationError",
    "OrderName",
    "OrdersChart",
    "OrdersChartRow",
    "RNGState",
    "TerrainType",
    "ValidationIssue",
    "are_adjacent",
    "attack_range_from_name",
    "british_forward_neighbors",
    "coordinate_system_from_name",
    "hex_direction_from_name",
    "is_terrain_name",
    "mission_objective_kind_from_name",
    "neighbor",
    "neighbors",
    "order_name_from_name",
    "terrain_from_name",
    "validate_mission",
]
